### ISSUE TITLE
Re-adding custom contract bindings

### ISSUE THREAD

**Issue by interzone2** [fxfactorial/liquidation-bot-fall-2020#1]
First, many thanks for opening sourcing your work. I am new to most of this and would like to learn.

Are the custom bindings these - if not what is the step to add them - custom contracts; these are custom contracts you wrote for each of the exchanges and the liq transactions ?:

	"watch_for_arb/adjustment/decimal"
	"watch_for_arb/common_flags"
	"watch_for_arb/contracts/aave/aave_price_oracle"
	"watch_for_arb/contracts/aave/lending_pool"
	"watch_for_arb/contracts/aave/lending_pool_addresses_provider"
	"watch_for_arb/contracts/aave/lending_pool_data_provider"
	"watch_for_arb/contracts/compound/cerc20"
	"watch_for_arb/contracts/compound/comptroller_g4"
	"watch_for_arb/contracts/custom_contracts/uniswap_flashloan_liquidate_aave"
	comp_based "watch_for_arb/contracts/custom_contracts/uniswap_flashloan_liquidate_comp_based"
	"watch_for_arb/contracts/erc20"
	"watch_for_arb/contracts/uniswap/pair"
	"watch_for_arb/contracts/uniswap/router"
	"watch_for_arb/mainnet_addrs"

**Comment by fxfactorial** [comment]
Sure - for the defi protocols , it’s in my other repo https://github.com/fxfactorial/defi-abigen

for the ones not there , I didn’t upload it cause it reveals too much
